In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from scipy import optimize
from ipywidgets import *
from IPython.display import SVG
from sklearn import datasets


In [2]:
# Lets Create a data for for making the neural Network Learn

In [3]:
AND = pd.DataFrame({'x1': (0,0,1,1), 'x2': (0,1,0,1), 'y': (0,0,0,1)})
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [4]:
inputs = AND[['x1','x2']]
target = AND['y']

In [5]:
inputs

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [6]:
#This is my original Y
target

0    0
1    0
2    0
3    1
Name: y, dtype: int64

First, we need to initialize weights to small, random values (can be positive and negative).

In [7]:
w = np.random.randn(3)*1e-4
w

array([ 7.17241309e-05, -6.25512947e-05,  1.14183123e-04])

In [8]:
#Creating an empty column to initilize the funtion with ones. Now our input data frame is ready

In [9]:
input1 = np.c_[inputs, -np.ones((len(inputs), 1))]
input1

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [ ]:
#Doing a dot matrix with the weights

In [10]:
np.dot(input1,w)

array([-1.14183123e-04, -1.76734418e-04, -4.24589924e-05, -1.05010287e-04])

# Giving my own activation fuction giving the following condition

In [11]:
g = lambda inputs, weights: np.where(np.dot(inputs, weights)>0, 1, 0)

In [12]:
# How our first output will look :
output =g(input1,w)
output

array([0, 0, 0, 0])

In [13]:
#So now finding the loss(here i have defined my own loss formula very simple, Not wusing, L1/L2/huger loss)
loss = output - target
loss

0    0
1    0
2    0
3   -1
Name: y, dtype: int64

# Finally, a training function that iterates the learning algorithm, returning the adapted weights.

In [14]:
def train(inputs, targets, weights, eta, n_iterations):

    # Add the inputs that match the bias node
    inputs = np.c_[inputs, -np.ones((len(inputs), 1))]

    for n in range(n_iterations):
        print(inputs)
        activations = g(inputs, weights);
        print(activations)
        weights -= eta*np.dot(np.transpose(inputs), activations - targets)
        print(weights)
    return(weights)

Taking learning rate as 0.25 and number of iterations as 10

In [15]:
inputs = AND[['x1','x2']]
target = AND['y']
w = train(inputs, target, w, 0.25, 10)

[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 0]
[ 0.25007172  0.24993745 -0.24988582]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[1 1 1 1]
[ 7.17241309e-05 -6.25512947e-05  5.00114183e-01]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 0]
[0.25007172 0.24993745 0.25011418]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
[0.25007172 0.24993745 0.25011418]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
[0.25007172 0.24993745 0.25011418]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
[0.25007172 0.24993745 0.25011418]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
[0.25007172 0.24993745 0.25011418]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
[0.25007172 0.24993745 0.25011418]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
[0.25007172 0.24993745 0.25011418]
[[ 0.  0. -1.]
 [ 0.  1. -1.